using DigitalTwin_Comms_PlcSimAdvanced.Constants;
using Siemens.Simatic.Simulation.Runtime;

namespace DigitalTwin_Comms_PlcSimAdvanced.Converters;

public static class ErrorCodeConverter
{
    public static ErrorCode ConvertErrorCode(ERuntimeErrorCode errorCode)
    {
        return errorCode switch
        {
            ERuntimeErrorCode.OK => ErrorCode.OK,
            ERuntimeErrorCode.InvalidErrorCode => ErrorCode.InvalidErrorCode,
            ERuntimeErrorCode.NotImplemented => ErrorCode.NotImplemented,
            ERuntimeErrorCode.IndexOutOfRange => ErrorCode.IndexOutOfRange,
            ERuntimeErrorCode.DoesNotExist => ErrorCode.DoesNotExist,
            ERuntimeErrorCode.AlreadyExists => ErrorCode.AlreadyExists,
            ERuntimeErrorCode.UnknownMessageType => ErrorCode.UnknownMessageType,
            ERuntimeErrorCode.InvalidMessageId => ErrorCode.InvalidMessageId,
            ERuntimeErrorCode.WrongArgument => ErrorCode.WrongArgument,
            ERuntimeErrorCode.WrongPipe => ErrorCode.WrongPipe,
            ERuntimeErrorCode.ConnectionError => ErrorCode.ConnectionError,
            ERuntimeErrorCode.Timeout => ErrorCode.Timeout,
            ERuntimeErrorCode.MessageCorrupt => ErrorCode.MessageCorrupt,
            ERuntimeErrorCode.WrongVersion => ErrorCode.WrongVersion,
            ERuntimeErrorCode.InstanceNotRunning => ErrorCode.InstanceNotRunning,
            ERuntimeErrorCode.InterfaceRemoved => ErrorCode.InterfaceRemoved,
            ERuntimeErrorCode.SharedMemoryNotInitialized => ErrorCode.SharedMemoryNotInitialized,
            ERuntimeErrorCode.ApiNotInitialized => ErrorCode.ApiNotInitialized,
            ERuntimeErrorCode.WarningAlreadyExists => ErrorCode.WarningAlreadyExists,
            ERuntimeErrorCode.NotSupported => ErrorCode.NotSupported,
            ERuntimeErrorCode.WarningInvalidCall => ErrorCode.WarningInvalidCall,
            ERuntimeErrorCode.ErrorLoadingDll => ErrorCode.ErrorLoadingDll,
            ERuntimeErrorCode.SignalNameDoesNotExist => ErrorCode.SignalNameDoesNotExist,
            ERuntimeErrorCode.SignalTypeMismatch => ErrorCode.SignalTypeMismatch,
            ERuntimeErrorCode.SignalConfigurationError => ErrorCode.SignalConfigurationError,
            ERuntimeErrorCode.NoSignalConfigurationLoaded => ErrorCode.NoSignalConfigurationLoaded,
            ERuntimeErrorCode.ConfiguredConnectionNotFound => ErrorCode.ConfiguredConnectionNotFound,
            ERuntimeErrorCode.ConfiguredDeviceNotFound => ErrorCode.ConfiguredDeviceNotFound,
            ERuntimeErrorCode.InvalidConfiguration => ErrorCode.InvalidConfiguration,
            ERuntimeErrorCode.TypeMismatch => ErrorCode.TypeMismatch,
            ERuntimeErrorCode.LicenseNotFound => ErrorCode.LicenseNotFound,
            ERuntimeErrorCode.NoLicenseAvailable => ErrorCode.NoLicenseAvailable,
            ERuntimeErrorCode.WrongCommunicationInterface => ErrorCode.WrongCommunicationInterface,
            ERuntimeErrorCode.LimitReached => ErrorCode.LimitReached,
            ERuntimeErrorCode.NoStoragePathSet => ErrorCode.NoStoragePathSet,
            ERuntimeErrorCode.StoragePathAlreadyInUse => ErrorCode.StoragePathAlreadyInUse,
            ERuntimeErrorCode.MessageIncomplete => ErrorCode.MessageIncomplete,
            ERuntimeErrorCode.ArchiveStorageNotCreated => ErrorCode.ArchiveStorageNotCreated,
            ERuntimeErrorCode.RetrieveStorageFailure => ErrorCode.RetrieveStorageFailure,
            ERuntimeErrorCode.InvalidOperatingState => ErrorCode.InvalidOperatingState,
            ERuntimeErrorCode.InvalidArchivePath => ErrorCode.InvalidArchivePath,
            ERuntimeErrorCode.DeleteExistingStorageFailed => ErrorCode.DeleteExistingStorageFailed,
            ERuntimeErrorCode.CreateDirectoriesFailed => ErrorCode.CreateDirectoriesFailed,
            ERuntimeErrorCode.NotEnoughMemory => ErrorCode.NotEnoughMemory,
            ERuntimeErrorCode.WarningTrialModeActive => ErrorCode.WarningTrialModeActive,
            ERuntimeErrorCode.NotRunning => ErrorCode.NotRunning,
            ERuntimeErrorCode.NotEmpty => ErrorCode.NotEmpty,
            ERuntimeErrorCode.NotUpToDate => ErrorCode.NotUpToDate,
            ERuntimeErrorCode.CommunicationInterfaceNotAvailable => ErrorCode.CommunicationInterfaceNotAvailable,
            ERuntimeErrorCode.WarningNotComplete => ErrorCode.WarningNotComplete,
            ERuntimeErrorCode.VirtualSwitchMisconfigured => ErrorCode.VirtualSwitchMisconfigured,
            ERuntimeErrorCode.RuntimeNotAvailable => ErrorCode.RuntimeNotAvailable,
            ERuntimeErrorCode.IsEmpty => ErrorCode.IsEmpty,
            ERuntimeErrorCode.WrongModuleState => ErrorCode.WrongModuleState,
            ERuntimeErrorCode.WrongModuleType => ErrorCode.WrongModuleType,
            ERuntimeErrorCode.NotSupportedByModule => ErrorCode.NotSupportedByModule,
            ERuntimeErrorCode.InternalError => ErrorCode.InternalError,
            ERuntimeErrorCode.StorageTransferError => ErrorCode.StorageTransferError,
            ERuntimeErrorCode.AnotherVariantOfPlcsimRunning => ErrorCode.AnotherVariantOfPlcsimRunning,
            ERuntimeErrorCode.AccessDenied => ErrorCode.AccessDenied,
            ERuntimeErrorCode.NotAllowedDuringDownload => ErrorCode.NotAllowedDuringDownload,
            ERuntimeErrorCode.AutodiscoverAlreadyRunning => ErrorCode.AutodiscoverAlreadyRunning,
            ERuntimeErrorCode.InvalidStorage => ErrorCode.InvalidStorage,
            ERuntimeErrorCode.WarningUnsupportedPcapDriver => ErrorCode.WarningUnsupportedPcapDriver,
            ERuntimeErrorCode.WarningRunningOnTiaPortalTestSuite => ErrorCode.WarningRunningOnTiaPortalTestSuite,
            ERuntimeErrorCode.PCAPDriverNotRunning => ErrorCode.PCAPDriverNotRunning,
            ERuntimeErrorCode.UnsupportedPcapDriver => ErrorCode.UnsupportedPcapDriver,
            ERuntimeErrorCode.ConfigFileError => ErrorCode.ConfigFileError,
            ERuntimeErrorCode.WarningPasswordForProtectionError => ErrorCode.WarningPasswordForProtectionError,
            ERuntimeErrorCode.BufferOverflow => ErrorCode.BufferOverflow,
            ERuntimeErrorCode.NotAllowed => ErrorCode.NotAllowed,
            ERuntimeErrorCode.WarningNoExternalCommunication => ErrorCode.WarningNoExternalCommunication,
            _ => throw new NotImplementedException(),
        };
    }

    public static ERuntimeErrorCode ConvertErrorCode(ErrorCode errorCode)
    {
        return errorCode switch
        {
            ErrorCode.OK => ERuntimeErrorCode.OK,
            ErrorCode.InvalidErrorCode => ERuntimeErrorCode.InvalidErrorCode,
            ErrorCode.NotImplemented => ERuntimeErrorCode.NotImplemented,
            ErrorCode.IndexOutOfRange => ERuntimeErrorCode.IndexOutOfRange,
            ErrorCode.DoesNotExist => ERuntimeErrorCode.DoesNotExist,
            ErrorCode.AlreadyExists => ERuntimeErrorCode.AlreadyExists,
            ErrorCode.UnknownMessageType => ERuntimeErrorCode.UnknownMessageType,
            ErrorCode.InvalidMessageId => ERuntimeErrorCode.InvalidMessageId,
            ErrorCode.WrongArgument => ERuntimeErrorCode.WrongArgument,
            ErrorCode.WrongPipe => ERuntimeErrorCode.WrongPipe,
            ErrorCode.ConnectionError => ERuntimeErrorCode.ConnectionError,
            ErrorCode.Timeout => ERuntimeErrorCode.Timeout,
            ErrorCode.MessageCorrupt => ERuntimeErrorCode.MessageCorrupt,
            ErrorCode.WrongVersion => ERuntimeErrorCode.WrongVersion,
            ErrorCode.InstanceNotRunning => ERuntimeErrorCode.InstanceNotRunning,
            ErrorCode.InterfaceRemoved => ERuntimeErrorCode.InterfaceRemoved,
            ErrorCode.SharedMemoryNotInitialized => ERuntimeErrorCode.SharedMemoryNotInitialized,
            ErrorCode.ApiNotInitialized => ERuntimeErrorCode.ApiNotInitialized,
            ErrorCode.WarningAlreadyExists => ERuntimeErrorCode.WarningAlreadyExists,
            ErrorCode.NotSupported => ERuntimeErrorCode.NotSupported,
            ErrorCode.WarningInvalidCall => ERuntimeErrorCode.WarningInvalidCall,
            ErrorCode.ErrorLoadingDll => ERuntimeErrorCode.ErrorLoadingDll,
            ErrorCode.SignalNameDoesNotExist => ERuntimeErrorCode.SignalNameDoesNotExist,
            ErrorCode.SignalTypeMismatch => ERuntimeErrorCode.SignalTypeMismatch,
            ErrorCode.SignalConfigurationError => ERuntimeErrorCode.SignalConfigurationError,
            ErrorCode.NoSignalConfigurationLoaded => ERuntimeErrorCode.NoSignalConfigurationLoaded,
            ErrorCode.ConfiguredConnectionNotFound => ERuntimeErrorCode.ConfiguredConnectionNotFound,
            ErrorCode.ConfiguredDeviceNotFound => ERuntimeErrorCode.ConfiguredDeviceNotFound,
            ErrorCode.InvalidConfiguration => ERuntimeErrorCode.InvalidConfiguration,
            ErrorCode.TypeMismatch => ERuntimeErrorCode.TypeMismatch,
            ErrorCode.LicenseNotFound => ERuntimeErrorCode.LicenseNotFound,
            ErrorCode.NoLicenseAvailable => ERuntimeErrorCode.NoLicenseAvailable,
            ErrorCode.WrongCommunicationInterface => ERuntimeErrorCode.WrongCommunicationInterface,
            ErrorCode.LimitReached => ERuntimeErrorCode.LimitReached,
            ErrorCode.NoStoragePathSet => ERuntimeErrorCode.NoStoragePathSet,
            ErrorCode.StoragePathAlreadyInUse => ERuntimeErrorCode.StoragePathAlreadyInUse,
            ErrorCode.MessageIncomplete => ERuntimeErrorCode.MessageIncomplete,
            ErrorCode.ArchiveStorageNotCreated => ERuntimeErrorCode.ArchiveStorageNotCreated,
            ErrorCode.RetrieveStorageFailure => ERuntimeErrorCode.RetrieveStorageFailure,
            ErrorCode.InvalidOperatingState => ERuntimeErrorCode.InvalidOperatingState,
            ErrorCode.InvalidArchivePath => ERuntimeErrorCode.InvalidArchivePath,
            ErrorCode.DeleteExistingStorageFailed => ERuntimeErrorCode.DeleteExistingStorageFailed,
            ErrorCode.CreateDirectoriesFailed => ERuntimeErrorCode.CreateDirectoriesFailed,
            ErrorCode.NotEnoughMemory => ERuntimeErrorCode.NotEnoughMemory,
            ErrorCode.WarningTrialModeActive => ERuntimeErrorCode.WarningTrialModeActive,
            ErrorCode.NotRunning => ERuntimeErrorCode.NotRunning,
            ErrorCode.NotEmpty => ERuntimeErrorCode.NotEmpty,
            ErrorCode.NotUpToDate => ERuntimeErrorCode.NotUpToDate,
            ErrorCode.CommunicationInterfaceNotAvailable => ERuntimeErrorCode.CommunicationInterfaceNotAvailable,
            ErrorCode.WarningNotComplete => ERuntimeErrorCode.WarningNotComplete,
            ErrorCode.VirtualSwitchMisconfigured => ERuntimeErrorCode.VirtualSwitchMisconfigured,
            ErrorCode.RuntimeNotAvailable => ERuntimeErrorCode.RuntimeNotAvailable,
            ErrorCode.IsEmpty => ERuntimeErrorCode.IsEmpty,
            ErrorCode.WrongModuleState => ERuntimeErrorCode.WrongModuleState,
            ErrorCode.WrongModuleType => ERuntimeErrorCode.WrongModuleType,
            ErrorCode.NotSupportedByModule => ERuntimeErrorCode.NotSupportedByModule,
            ErrorCode.InternalError => ERuntimeErrorCode.InternalError,
            ErrorCode.StorageTransferError => ERuntimeErrorCode.StorageTransferError,
            ErrorCode.AnotherVariantOfPlcsimRunning => ERuntimeErrorCode.AnotherVariantOfPlcsimRunning,
            ErrorCode.AccessDenied => ERuntimeErrorCode.AccessDenied,
            ErrorCode.NotAllowedDuringDownload => ERuntimeErrorCode.NotAllowedDuringDownload,
            ErrorCode.AutodiscoverAlreadyRunning => ERuntimeErrorCode.AutodiscoverAlreadyRunning,
            ErrorCode.InvalidStorage => ERuntimeErrorCode.InvalidStorage,
            ErrorCode.WarningUnsupportedPcapDriver => ERuntimeErrorCode.WarningUnsupportedPcapDriver,
            ErrorCode.WarningRunningOnTiaPortalTestSuite => ERuntimeErrorCode.WarningRunningOnTiaPortalTestSuite,
            ErrorCode.PCAPDriverNotRunning => ERuntimeErrorCode.PCAPDriverNotRunning,
            ErrorCode.UnsupportedPcapDriver => ERuntimeErrorCode.UnsupportedPcapDriver,
            ErrorCode.ConfigFileError => ERuntimeErrorCode.ConfigFileError,
            ErrorCode.WarningPasswordForProtectionError => ERuntimeErrorCode.WarningPasswordForProtectionError,
            ErrorCode.BufferOverflow => ERuntimeErrorCode.BufferOverflow,
            ErrorCode.NotAllowed => ERuntimeErrorCode.NotAllowed,
            ErrorCode.WarningNoExternalCommunication => ERuntimeErrorCode.WarningNoExternalCommunication,
            _ => throw new NotImplementedException(),
        };
    }
}