using DigitalTwin_Comms_PlcSimAdvanced.Constants;
using Siemens.Simatic.Simulation.Runtime;

namespace DigitalTwin_Comms_PlcSimAdvanced.Converters;

public static class ErrorCodeTypeConverter
{
    public static ErrorCodeType ConvertErrorCode(ERuntimeErrorCode errorCode)
    {
        return errorCode switch
        {
            ERuntimeErrorCode.OK => ErrorCodeType.OK,
            ERuntimeErrorCode.InvalidErrorCode => ErrorCodeType.InvalidErrorCode,
            ERuntimeErrorCode.NotImplemented => ErrorCodeType.NotImplemented,
            ERuntimeErrorCode.IndexOutOfRange => ErrorCodeType.IndexOutOfRange,
            ERuntimeErrorCode.DoesNotExist => ErrorCodeType.DoesNotExist,
            ERuntimeErrorCode.AlreadyExists => ErrorCodeType.AlreadyExists,
            ERuntimeErrorCode.UnknownMessageType => ErrorCodeType.UnknownMessageType,
            ERuntimeErrorCode.InvalidMessageId => ErrorCodeType.InvalidMessageId,
            ERuntimeErrorCode.WrongArgument => ErrorCodeType.WrongArgument,
            ERuntimeErrorCode.WrongPipe => ErrorCodeType.WrongPipe,
            ERuntimeErrorCode.ConnectionError => ErrorCodeType.ConnectionError,
            ERuntimeErrorCode.Timeout => ErrorCodeType.Timeout,
            ERuntimeErrorCode.MessageCorrupt => ErrorCodeType.MessageCorrupt,
            ERuntimeErrorCode.WrongVersion => ErrorCodeType.WrongVersion,
            ERuntimeErrorCode.InstanceNotRunning => ErrorCodeType.InstanceNotRunning,
            ERuntimeErrorCode.InterfaceRemoved => ErrorCodeType.InterfaceRemoved,
            ERuntimeErrorCode.SharedMemoryNotInitialized => ErrorCodeType.SharedMemoryNotInitialized,
            ERuntimeErrorCode.ApiNotInitialized => ErrorCodeType.ApiNotInitialized,
            ERuntimeErrorCode.WarningAlreadyExists => ErrorCodeType.WarningAlreadyExists,
            ERuntimeErrorCode.NotSupported => ErrorCodeType.NotSupported,
            ERuntimeErrorCode.WarningInvalidCall => ErrorCodeType.WarningInvalidCall,
            ERuntimeErrorCode.ErrorLoadingDll => ErrorCodeType.ErrorLoadingDll,
            ERuntimeErrorCode.SignalNameDoesNotExist => ErrorCodeType.SignalNameDoesNotExist,
            ERuntimeErrorCode.SignalTypeMismatch => ErrorCodeType.SignalTypeMismatch,
            ERuntimeErrorCode.SignalConfigurationError => ErrorCodeType.SignalConfigurationError,
            ERuntimeErrorCode.NoSignalConfigurationLoaded => ErrorCodeType.NoSignalConfigurationLoaded,
            ERuntimeErrorCode.ConfiguredConnectionNotFound => ErrorCodeType.ConfiguredConnectionNotFound,
            ERuntimeErrorCode.ConfiguredDeviceNotFound => ErrorCodeType.ConfiguredDeviceNotFound,
            ERuntimeErrorCode.InvalidConfiguration => ErrorCodeType.InvalidConfiguration,
            ERuntimeErrorCode.TypeMismatch => ErrorCodeType.TypeMismatch,
            ERuntimeErrorCode.LicenseNotFound => ErrorCodeType.LicenseNotFound,
            ERuntimeErrorCode.NoLicenseAvailable => ErrorCodeType.NoLicenseAvailable,
            ERuntimeErrorCode.WrongCommunicationInterface => ErrorCodeType.WrongCommunicationInterface,
            ERuntimeErrorCode.LimitReached => ErrorCodeType.LimitReached,
            ERuntimeErrorCode.NoStoragePathSet => ErrorCodeType.NoStoragePathSet,
            ERuntimeErrorCode.StoragePathAlreadyInUse => ErrorCodeType.StoragePathAlreadyInUse,
            ERuntimeErrorCode.MessageIncomplete => ErrorCodeType.MessageIncomplete,
            ERuntimeErrorCode.ArchiveStorageNotCreated => ErrorCodeType.ArchiveStorageNotCreated,
            ERuntimeErrorCode.RetrieveStorageFailure => ErrorCodeType.RetrieveStorageFailure,
            ERuntimeErrorCode.InvalidOperatingState => ErrorCodeType.InvalidOperatingState,
            ERuntimeErrorCode.InvalidArchivePath => ErrorCodeType.InvalidArchivePath,
            ERuntimeErrorCode.DeleteExistingStorageFailed => ErrorCodeType.DeleteExistingStorageFailed,
            ERuntimeErrorCode.CreateDirectoriesFailed => ErrorCodeType.CreateDirectoriesFailed,
            ERuntimeErrorCode.NotEnoughMemory => ErrorCodeType.NotEnoughMemory,
            ERuntimeErrorCode.WarningTrialModeActive => ErrorCodeType.WarningTrialModeActive,
            ERuntimeErrorCode.NotRunning => ErrorCodeType.NotRunning,
            ERuntimeErrorCode.NotEmpty => ErrorCodeType.NotEmpty,
            ERuntimeErrorCode.NotUpToDate => ErrorCodeType.NotUpToDate,
            ERuntimeErrorCode.CommunicationInterfaceNotAvailable => ErrorCodeType.CommunicationInterfaceNotAvailable,
            ERuntimeErrorCode.WarningNotComplete => ErrorCodeType.WarningNotComplete,
            ERuntimeErrorCode.VirtualSwitchMisconfigured => ErrorCodeType.VirtualSwitchMisconfigured,
            ERuntimeErrorCode.RuntimeNotAvailable => ErrorCodeType.RuntimeNotAvailable,
            ERuntimeErrorCode.IsEmpty => ErrorCodeType.IsEmpty,
            ERuntimeErrorCode.WrongModuleState => ErrorCodeType.WrongModuleState,
            ERuntimeErrorCode.WrongModuleType => ErrorCodeType.WrongModuleType,
            ERuntimeErrorCode.NotSupportedByModule => ErrorCodeType.NotSupportedByModule,
            ERuntimeErrorCode.InternalError => ErrorCodeType.InternalError,
            ERuntimeErrorCode.StorageTransferError => ErrorCodeType.StorageTransferError,
            ERuntimeErrorCode.AnotherVariantOfPlcsimRunning => ErrorCodeType.AnotherVariantOfPlcsimRunning,
            ERuntimeErrorCode.AccessDenied => ErrorCodeType.AccessDenied,
            ERuntimeErrorCode.NotAllowedDuringDownload => ErrorCodeType.NotAllowedDuringDownload,
            ERuntimeErrorCode.AutodiscoverAlreadyRunning => ErrorCodeType.AutodiscoverAlreadyRunning,
            ERuntimeErrorCode.InvalidStorage => ErrorCodeType.InvalidStorage,
            ERuntimeErrorCode.WarningUnsupportedPcapDriver => ErrorCodeType.WarningUnsupportedPcapDriver,
            ERuntimeErrorCode.WarningRunningOnTiaPortalTestSuite => ErrorCodeType.WarningRunningOnTiaPortalTestSuite,
            ERuntimeErrorCode.PCAPDriverNotRunning => ErrorCodeType.PCAPDriverNotRunning,
            ERuntimeErrorCode.UnsupportedPcapDriver => ErrorCodeType.UnsupportedPcapDriver,
            ERuntimeErrorCode.ConfigFileError => ErrorCodeType.ConfigFileError,
            ERuntimeErrorCode.WarningPasswordForProtectionError => ErrorCodeType.WarningPasswordForProtectionError,
            ERuntimeErrorCode.BufferOverflow => ErrorCodeType.BufferOverflow,
            ERuntimeErrorCode.NotAllowed => ErrorCodeType.NotAllowed,
            ERuntimeErrorCode.WarningNoExternalCommunication => ErrorCodeType.WarningNoExternalCommunication,
            _ => throw new NotImplementedException(),
        };
    }
}